fix audio of pong game
WildCodeSchool/2023-02-Orleans-Spe-P2-A pull request #6
Opened 2023-03-19 09:58 UTC by Richarddesnoues

2023-03-19 10:38 UTC, Ga-Mikael approved these changes, later dismissed

2023-03-19 12:05 UTC, YDrogen requested changes

2023-03-19 12:05 UTC, YDrogen commented on src/js/Pong.js
> +        this.chrono = 50;
Espace qui sert à rien ?

2023-03-19 12:05 UTC, YDrogen commented on src/js/Pong.js
> +
2 lignes vides ?

2023-03-19 12:05 UTC, YDrogen commented on src/js/Pong.js
> +            this.physics.world.bounds.height / 2,
idem ?

2023-03-19 21:03 UTC, YDrogen requested changes

2023-03-19 21:03 UTC, YDrogen commented on src/js/Pong.js
> +        this.load.audio('PongPeep', './src/assets/pong_sound/peeeeeep.ogg');
Espace qui sert à rien ?

2023-03-19 21:03 UTC, YDrogen commented on src/js/Start.js
> +
```suggestion

```
Espace inutile; ok pour la ligne, mais vide

2023-03-20 08:42 UTC, Ga-Mikael approved these changes, later dismissed

2023-03-20 08:45 UTC, YDrogen requested changes

2023-03-20 08:45 UTC, YDrogen commented on src/js/Pong.js
> +        this.load.audio('PongPeep', './src/assets/pong_sound/peeeeeep.ogg');
espaces vides

2023-03-20 09:03 UTC, Ga-Mikael submitted a review, later dismissed

2023-03-20 09:27 UTC, YDrogen requested changes

2023-03-20 09:27 UTC, YDrogen commented on src/js/EndGame.js
> +        let endBcg = document.getElementById('game-div');
const

2023-03-20 09:33 UTC, Ga-Mikael approved these changes

2023-03-20 09:37 UTC, YDrogen approved these changes

2023-03-20 09:37 UTC, merged